# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: open-sdg/open-sdg@2.1.0

# Replace this title as needed.
title: general.site_title
url: ""
environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

frontpage_cards:
  - 
    title: frontpage.download_all
    include: components/download-all-data.html
    
  - 
    title: frontpage.second_header
    content: frontpage.second_content
#    button_label: custom.access
#    button_link: custom.gif_link
    
  - 
    title: frontpage.third_header
    content: frontpage.third_content
      
#    button_label: custom.access
#    button_link: custom.about_link

  

