accessible_charts: true
accessible_tabs: true
analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - label: general.home
      path: /
 #   - label: menu.updates
 #     path: /news
contrast_type: default
cookie_consent_form:
  enabled: false
country:
  name: Canada
  adjective: Canadian
create_goals:
  layout: goal-with-progress
  previous_next_links: true
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: ''
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: statcan.sdg-odd.statcan@statcan.gc.ca
  suggestions: statcan.sdg-odd.statcan@statcan.gc.ca
  functional: statcan.sdg-odd.statcan@statcan.gc.ca
environment: staging
favicons: favicon.io
footer_language_toggle: none

footer_menu:
  - path: mailto:statcan.sdg-odd.statcan@statcan.gc.ca
    translation_key: menu.contact_us
  - path: general.facebook_link
    translation_key: general.facebook
  - path: general.instagram_link
    translation_key: general.instagram
  - path: general.linkedin_link
    translation_key: general.linkedin
  - path: general.reddit_link
    translation_key: general.reddit
  - path: general.twitter_link
    translation_key: general.twitter
  - path: general.youtube_link
    translation_key: general.youtube
  - path: general.statcan_link
    translation_key: general.statcan
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
    
  - title: frontpage.second_header
    content: frontpage.second_content
    #include: ''
    #button_label: frontpage.second_text
    #button_link: frontpage.second_link
    #rule_color: ''

  - title: frontpage.third_header
    content: frontpage.third_content
    #include: ''
    #button_label: frontpage.third_text
    #button_link: frontpage.third_link
    #rule_color: ''

frontpage_goals_grid:
  title: frontpage.heading
  description: frontpage.instructions
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: general.goal_description
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
ignored_disaggregations:
  - Progress
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/indicator-config'
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: '/tree/develop/data'
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/meta'
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
languages:
  - en
  - fr
languages_public: []
logos: 
  - language: en
    src: assets/img/EN_SDG_logo_transparent.png
    alt: Go to home page
  - language: fr
    src: assets/img/fr/FR_SDG_logo_transparent.png
    alt: Aller à la page d'accueil

map_options:
  # Whether the map should provide a button and form for changing the displayed disaggregation:
  disaggregation_controls: true
  minZoom: 2
  maxZoom: 6
  tileURL: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
  tileOptions:
    id: ''
    accessToken: ''
    attribution: <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#deebf7'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#3182bd'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
map_layers:
  - min_zoom: 2
    max_zoom: 6
    subfolder: regions
    label: Regions
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  # - path: menu.cif_hub_url
  #   translation_key: menu.cif_hub
  #   dropdown: []
  - translation_key: menu.more_info
    dropdown:
      - path: /related-products
        translation_key: menu.related-products
#      - path: /methodology
#        translation_key: menu.methodology
#  - path: /news
#    translation_key: menu.updates
#    dropdown: []
metadata_edit_url: ''
metadata_tabs: []
#  - scope: national
#    title: indicator.national_metadata
#    description: ''
#  - scope: sources_alt
#    title: indicator.sources
#    description: ''
#  - scope: global
#    title: indicator.global_metadata
#    description: ''
news:
  category_links: false
non_global_metadata: indicator.national_metadata
observation_attributes:
  - field: COMMENT_OBS
    label: ''
  - field: COMMENT_OBS_0
    label: ''
  - field: COMMENT_OBS_1
    label: ''
  - field: COMMENT_OBS_2
    label: ''
#progress_status:
#    status_heading: Progress status
#    status_types:
##      - value: not_available
##        label: status.progress_not_available
##        image: assets/img/progress/not-available.png
##        alt: status.progress_not_available
#      - value: target_achieved
#        label: status.progress_target_achieved
#        image: assets/img/progress/target-achieved-gauge.png
#        alt: status.progress_target_achieved
#      - value: substantial_progress
#        label: status.substantial_progress
#        image: assets/img/progress/green-gauge.png
#        alt: status.substantial_progress
#      - value: moderate_progress
#        label: status.moderate_progress
#        image: assets/img/progress/yellow-gauge.png
#        alt: status.moderate_progress
#      - value: negligible_progress
#        label: status.negligible_progress
#        image: assets/img/progress/orange-gauge.png
#        alt: status.negligible_progress
#      - value: deterioration
#        label: status.deterioration
#        image: assets/img/progress/red-gauge.png
#        alt: status.deterioration
#      - value: moderate_deterioration
#        label: status.moderate_deterioration
#        image: assets/img/progress/orange-gauge.png
#        alt: status.moderate_deterioration
#      - value: significant_deterioration
#        label: status.significant_deterioration
#        image: assets/img/progress/red-gauge.png
#        alt: status.significant_deterioration
        
remote_data_prefix: 'https://sdg-data-canada-odd-donnees.github.io/sdg-data-donnees-odd/'
reporting_status:
  title: status.reporting_status
  description: status.status_description
  disaggregation_tabs: true
  status_types:
    - value: notstarted
      label: status.exploring_data_sources
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
    - value: notavailable
      label: status.not_available
      hide_on_goal_pages: false
  disaggregation_indicator_count_label: indicators in scope
repository_url_data: 'https://github.com/open-sdg/open-sdg-data-starter'
repository_url_site: ''
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: '/tree/develop/_data'
  translation_link: ''
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
