# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
#
# For example, if your production organisation is "my-stats-org", then use:
#
# REPOSITORY_NAME: my-stats-org/my-stats-org.github.io
#
# ****************************************************************************

name: Deploy to production
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true   # handles `bundle install` + caching automatically

      - name: Build the site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --config _config.yml,_config_prod.yml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: sdggif-data-canada-oddcmi-donnee/sdggif-data-canada-oddcmi-donnee.github.io
          token: ${{ secrets.token }}
          branch: master
          folder: _site
          clean: true
